title: MerelyLogical
description: Personal blog
author: MerelyLogical

theme: jekyll-theme-cayman

github_username: MerelyLogical

collections:
  pages:
    output: true

exclude:
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
